#!/usr/bin/env python3
"""Generate the MFC42 ordinal map and the tracing stubs.

Implemented functions are marked in mfc42.c with a /*ORD n*/ marker just
before the definition.  Everything depends.exe imports that is not yet
implemented gets a stub that reports itself, so the DLL always exports the
full set of 433 ordinals and the application can keep running.
"""
import re, struct, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))

def imported_ordinals(path):
    d = open(path, 'rb').read()
    pe = struct.unpack('<I', d[0x3c:0x40])[0]; oh = pe + 24
    nsec = struct.unpack('<H', d[pe+6:pe+8])[0]
    ohsz = struct.unpack('<H', d[pe+20:pe+22])[0]
    irva, _ = struct.unpack('<II', d[oh+112+8:oh+112+16])
    sh = pe + 24 + ohsz; secs = []
    for i in range(nsec):
        s = sh + 40*i
        vs, rva, raw, po = struct.unpack('<IIII', d[s+8:s+24])
        secs.append((rva, vs, po))
    def r2o(r):
        for rva, vs, po in secs:
            if rva <= r < rva+vs: return po + (r - rva)
    o = r2o(irva); ords = []
    while True:
        oft, tds, fc, nm, ft = struct.unpack('<IIIII', d[o:o+20])
        if nm == 0 and ft == 0: break
        so = r2o(nm); e = d.index(b'\0', so)
        if d[so:e].decode().upper() == 'MFC42.DLL':
            t = r2o(oft or ft)
            while True:
                ent = struct.unpack('<Q', d[t:t+8])[0]
                if ent == 0: break
                if ent >> 63: ords.append(ent & 0xFFFF)
                t += 8
        o += 20
    return sorted(set(ords))

def implemented(src):
    """ordinal -> C symbol, from /*ORD n*/ markers."""
    text = open(src).read()
    out = {}
    for m in re.finditer(r'/\*ORD\s+(\d+)\s*\*/\s*[\w \t*]*?([A-Za-z_]\w*)\s*\(', text):
        out[int(m.group(1))] = m.group(2)
    return out

def main():
    exe = sys.argv[1] if len(sys.argv) > 1 else '/home/claude/work/axp64/depends.exe'
    ords = imported_ordinals(exe)
    impl = implemented(os.path.join(HERE, 'mfc42.c'))
    # ordinals that must be exported as DATA (message maps depends.exe chains
    # into via its own pBaseMap pointers)
    datamaps = {}
    dm = os.path.join(HERE, 'mfc42.datamaps')
    if os.path.exists(dm):
        for line in open(dm):
            line = line.split('#')[0].strip()
            if line:
                o, _, rest = line.partition('=')
                datamaps[int(o)] = rest
    todo = [o for o in ords if o not in impl and o not in datamaps]

    src = ['/* generated by genmfc.py - tracing stubs for unimplemented ordinals */',
           'typedef long long LL;',
           'extern LL __mfc_trace(LL ord, LL a0, LL a1, LL a2, LL a3, LL a4,'
           '                      LL a5, LL a6, LL a7);', '']
    for o in todo:
        src.append(f'LL mfc_{o}(LL a,LL b,LL c,LL d,LL e,LL f,LL g,LL h)'
                   f'{{ return __mfc_trace({o},a,b,c,d,e,f,g,h); }}')
    open(os.path.join(HERE, 'mfc42_stub.c'), 'w').write('\n'.join(src) + '\n')

    with open(os.path.join(HERE, 'mfc42.ords'), 'w') as f:
        for o in ords:
            if o in datamaps:
                f.write(f'{o}={datamaps[o]}\n')
            else:
                f.write(f'{o}={impl.get(o, "mfc_%d" % o)}\n')

    done = [o for o in ords if o in impl]
    print(f'{len(ords)} ordinals: {len(done)} implemented, '
          f'{len(datamaps)} data maps, {len(todo)} stubbed')

if __name__ == '__main__':
    main()
